// const element = document.getElementById('click')
// console.log(element)
// const header = document.getElementsByClassName('heading')
// console.log(header)
const element = document.querySelector('.heading')
console.log(element)