console.log('hey u are u there')
console.log(true)
console.log(2409686743896823)
console.log(false)
console.log("fgvefdf")
console.log(false)
console.log("wrtefg",true,false,1325)
console.warn("this is warning")
console.error("this is error")